version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "8050:8050"
    volumes:
      - ./data:/src/data
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
